spring:
  datasource:
    url: jdbc:mysql://172.18.0.1:3306/shop?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    user: root
    password: root
    baseline-version: 0

init-db: fasle